clear
load nnet;
imds = imageDatastore("/Users/kavya/Desktop/Clip_Files",...
    'IncludeSubfolders', true, ...
    'LabelSource', 'foldernames');

%creating training versus testing 
[imdsTrain,imdsValidation]= splitEachLabel(imds, 0.8);

%algorithm parameters
options= trainingOptions('sgdm',...
    'MiniBatchSize',16,...
    'MaxEpochs',6,...
    'InitialLearnRate',1e-5,...
    'Shuffle','every-epoch',...
    'ValidationData',imdsValidation,...
    'ValidationFrequency',3,...
    'Verbose',false,...
    'Plots','training-progress');
%training
net=trainNetwork(imdsTrain,layers_1,options);


    